.class public abstract Lcom/lody/virtual/client/stub/StubDialog;
.super Lcom/lody/virtual/client/stub/StubActivity;
.source "StubDialog.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/lody/virtual/client/stub/StubDialog$C99;,
        Lcom/lody/virtual/client/stub/StubDialog$C98;,
        Lcom/lody/virtual/client/stub/StubDialog$C97;,
        Lcom/lody/virtual/client/stub/StubDialog$C96;,
        Lcom/lody/virtual/client/stub/StubDialog$C95;,
        Lcom/lody/virtual/client/stub/StubDialog$C94;,
        Lcom/lody/virtual/client/stub/StubDialog$C93;,
        Lcom/lody/virtual/client/stub/StubDialog$C92;,
        Lcom/lody/virtual/client/stub/StubDialog$C91;,
        Lcom/lody/virtual/client/stub/StubDialog$C90;,
        Lcom/lody/virtual/client/stub/StubDialog$C89;,
        Lcom/lody/virtual/client/stub/StubDialog$C88;,
        Lcom/lody/virtual/client/stub/StubDialog$C87;,
        Lcom/lody/virtual/client/stub/StubDialog$C86;,
        Lcom/lody/virtual/client/stub/StubDialog$C85;,
        Lcom/lody/virtual/client/stub/StubDialog$C84;,
        Lcom/lody/virtual/client/stub/StubDialog$C83;,
        Lcom/lody/virtual/client/stub/StubDialog$C82;,
        Lcom/lody/virtual/client/stub/StubDialog$C81;,
        Lcom/lody/virtual/client/stub/StubDialog$C80;,
        Lcom/lody/virtual/client/stub/StubDialog$C79;,
        Lcom/lody/virtual/client/stub/StubDialog$C78;,
        Lcom/lody/virtual/client/stub/StubDialog$C77;,
        Lcom/lody/virtual/client/stub/StubDialog$C76;,
        Lcom/lody/virtual/client/stub/StubDialog$C75;,
        Lcom/lody/virtual/client/stub/StubDialog$C74;,
        Lcom/lody/virtual/client/stub/StubDialog$C73;,
        Lcom/lody/virtual/client/stub/StubDialog$C72;,
        Lcom/lody/virtual/client/stub/StubDialog$C71;,
        Lcom/lody/virtual/client/stub/StubDialog$C70;,
        Lcom/lody/virtual/client/stub/StubDialog$C69;,
        Lcom/lody/virtual/client/stub/StubDialog$C68;,
        Lcom/lody/virtual/client/stub/StubDialog$C67;,
        Lcom/lody/virtual/client/stub/StubDialog$C66;,
        Lcom/lody/virtual/client/stub/StubDialog$C65;,
        Lcom/lody/virtual/client/stub/StubDialog$C64;,
        Lcom/lody/virtual/client/stub/StubDialog$C63;,
        Lcom/lody/virtual/client/stub/StubDialog$C62;,
        Lcom/lody/virtual/client/stub/StubDialog$C61;,
        Lcom/lody/virtual/client/stub/StubDialog$C60;,
        Lcom/lody/virtual/client/stub/StubDialog$C59;,
        Lcom/lody/virtual/client/stub/StubDialog$C58;,
        Lcom/lody/virtual/client/stub/StubDialog$C57;,
        Lcom/lody/virtual/client/stub/StubDialog$C56;,
        Lcom/lody/virtual/client/stub/StubDialog$C55;,
        Lcom/lody/virtual/client/stub/StubDialog$C54;,
        Lcom/lody/virtual/client/stub/StubDialog$C53;,
        Lcom/lody/virtual/client/stub/StubDialog$C52;,
        Lcom/lody/virtual/client/stub/StubDialog$C51;,
        Lcom/lody/virtual/client/stub/StubDialog$C50;,
        Lcom/lody/virtual/client/stub/StubDialog$C49;,
        Lcom/lody/virtual/client/stub/StubDialog$C48;,
        Lcom/lody/virtual/client/stub/StubDialog$C47;,
        Lcom/lody/virtual/client/stub/StubDialog$C46;,
        Lcom/lody/virtual/client/stub/StubDialog$C45;,
        Lcom/lody/virtual/client/stub/StubDialog$C44;,
        Lcom/lody/virtual/client/stub/StubDialog$C43;,
        Lcom/lody/virtual/client/stub/StubDialog$C42;,
        Lcom/lody/virtual/client/stub/StubDialog$C41;,
        Lcom/lody/virtual/client/stub/StubDialog$C40;,
        Lcom/lody/virtual/client/stub/StubDialog$C39;,
        Lcom/lody/virtual/client/stub/StubDialog$C38;,
        Lcom/lody/virtual/client/stub/StubDialog$C37;,
        Lcom/lody/virtual/client/stub/StubDialog$C36;,
        Lcom/lody/virtual/client/stub/StubDialog$C35;,
        Lcom/lody/virtual/client/stub/StubDialog$C34;,
        Lcom/lody/virtual/client/stub/StubDialog$C33;,
        Lcom/lody/virtual/client/stub/StubDialog$C32;,
        Lcom/lody/virtual/client/stub/StubDialog$C31;,
        Lcom/lody/virtual/client/stub/StubDialog$C30;,
        Lcom/lody/virtual/client/stub/StubDialog$C29;,
        Lcom/lody/virtual/client/stub/StubDialog$C28;,
        Lcom/lody/virtual/client/stub/StubDialog$C27;,
        Lcom/lody/virtual/client/stub/StubDialog$C26;,
        Lcom/lody/virtual/client/stub/StubDialog$C25;,
        Lcom/lody/virtual/client/stub/StubDialog$C24;,
        Lcom/lody/virtual/client/stub/StubDialog$C23;,
        Lcom/lody/virtual/client/stub/StubDialog$C22;,
        Lcom/lody/virtual/client/stub/StubDialog$C21;,
        Lcom/lody/virtual/client/stub/StubDialog$C20;,
        Lcom/lody/virtual/client/stub/StubDialog$C19;,
        Lcom/lody/virtual/client/stub/StubDialog$C18;,
        Lcom/lody/virtual/client/stub/StubDialog$C17;,
        Lcom/lody/virtual/client/stub/StubDialog$C16;,
        Lcom/lody/virtual/client/stub/StubDialog$C15;,
        Lcom/lody/virtual/client/stub/StubDialog$C14;,
        Lcom/lody/virtual/client/stub/StubDialog$C13;,
        Lcom/lody/virtual/client/stub/StubDialog$C12;,
        Lcom/lody/virtual/client/stub/StubDialog$C11;,
        Lcom/lody/virtual/client/stub/StubDialog$C10;,
        Lcom/lody/virtual/client/stub/StubDialog$C9;,
        Lcom/lody/virtual/client/stub/StubDialog$C8;,
        Lcom/lody/virtual/client/stub/StubDialog$C7;,
        Lcom/lody/virtual/client/stub/StubDialog$C6;,
        Lcom/lody/virtual/client/stub/StubDialog$C5;,
        Lcom/lody/virtual/client/stub/StubDialog$C4;,
        Lcom/lody/virtual/client/stub/StubDialog$C3;,
        Lcom/lody/virtual/client/stub/StubDialog$C2;,
        Lcom/lody/virtual/client/stub/StubDialog$C1;,
        Lcom/lody/virtual/client/stub/StubDialog$C0;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    .line 7
    invoke-direct {p0}, Lcom/lody/virtual/client/stub/StubActivity;-><init>()V

    return-void
.end method
